### ISSUE TITLE
Fix for webdiscus/pug-loader

### ISSUE THREAD

**Issue by webdiscus** [daomatys/metalamp-fedsec-layouts#1]
Hello Maxim,

I have fixed the `@webdiscus/pug-loader` for usage with absolute inclusion in pug template.
The @webdiscus/pug-loader v1.5.0 has new option `basedir`. This option name uses in [pug API](https://pugjs.org/api/reference.html).

I know, the `simple-pug-loader` use both names `root` || `basedir`, but `basedir` is default name.

### Changes:

package.json
 ```
 "@webdiscus/pug-loader": "^1.5.0",
```

webpack.config.js
```
{
  test: /\.pug$/i,
  loader: 'aliased-pug-loader',
  options: {
    basedir: PATHS.src, // add this  option for webdiscus/pug-loader
    root: PATHS.src,
    pretty: true
  }
},

...

resolveLoader: {
  alias: {
    //'aliased-pug-loader': 'simple-pug-loader'
    'aliased-pug-loader': '@webdiscus/pug-loader', // now it works :-)
  }
}
```

P.S. You can open [new  issue](https://github.com/webdiscus/pug-loader/issues) in my repository. 
Thank You for this layout! 👍🏻

**Comment by daomatys** [comment]
Hello, @webdiscus,

Thank you for such an unexpected attention to my repository!

Gonna test that new feature out right now, and send you a feedback later.
